### ISSUE TITLE
This is a great-looking project!  How do I run it?

### ISSUE THREAD

**Issue by Tylersuard** [kevalmorabia97/CoVA-Web-Object-Detection#8]
Hello, can you give me an example command for how to run inference on an image?  The documentation provides no examples.

**Comment by kevalmorabia97** [comment]
You can run `https://github.com/kevalmorabia97/CoVA-Web-Object-Detection/blob/master/evaluate.py` to evaluate a trained model on given test dataset split.

**Comment by Tylersuard** [comment]
Sorry, I am confused.  I want to take one screenshot of a website and run inference on it using your program.  How would I do that?

**Comment by Tylersuard** [comment]
I tried your solution and I got this error:

Traceback (most recent call last):
  File "evaluate.py", line 159, in <module>
    ), "Model does not seem to have been trained (run main.py) with the hyperparameters you provided"
AssertionError: Model does not seem to have been trained (run main.py) with the hyperparameters you provided

**Comment by kevalmorabia97** [comment]
The model takes a screenshot and bounding box proposals (obtained by parsing the HTML. There are many libraries available to do that). You need to setup your test dataset in the required format then you can run `evaluate.py`

The assertion error means it cannot find the trained model since it is not trained
